spring.application.name=finance-manage-system
spring.datasource.url=jdbc:postgresql://localhost:5432/finance_manage_system
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=validate

security.jwt.secret=TKzxfhTWIzfUUcyd3UOsCGU3ooqzDT2FFYHEdHAYYMFVBgPZ0_zZJpNIwdS_wiSSOC1CIjZ5wQItp6BMAe3GMA
security.jwt.expiration=7200000