spring.application.name=finance-manage-system
spring.datasource.url=jdbc:postgresql://localhost:5432/finance_manage_system
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.database=finance_manage_system
spring.jpa.hibernate.ddl-auto=validate
