spring.application.name=finance-manage-system
spring.datasource.url=jdbc:postgresql://127.0.0.1:5433/finance_manage_system
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=validate

logging.level.org.springframework.boot.context.config=DEBUG

logging.level.org.flywaydb=DEBUG